# -*- coding: utf-8 -*-
"""Ciber0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CX6Aus7z2G1gbM9NhXPecycdalSlE_nt
"""

# Importa todas las letras del alfabeto (mayúsculas + minúsculas)
from string import ascii_letters

# Bucle anidado que recorre todas las combinaciones posibles de 4 letras
for i in ascii_letters:
    for j in ascii_letters:
        for k in ascii_letters:
            for l in ascii_letters:
                print(i, j, k, l)  # Imprime una combinación de 4 letras (por ejemplo: A b C d)

from string import ascii_letters, digits, punctuation

for i in ascii_letters + digits + punctuation:
    for j in ascii_letters + digits + punctuation:
        for k in ascii_letters + digits + punctuation:
            for l in ascii_letters + digits + punctuation:
                print(i, j, k, l)

from string import ascii_letters, digits, punctuation
# Importa tres conjuntos de caracteres:
# ascii_letters: letras mayúsculas y minúsculas (A–Z, a–z)
# digits: números del 0 al 9
# punctuation: símbolos como !@#$%^&*()_+ etc.

# Bucle anidado que genera todas las combinaciones posibles de 4 caracteres
# usando letras, dígitos y símbolos
for i in ascii_letters + digits + punctuation:
    for j in ascii_letters + digits + punctuation:
        for k in ascii_letters + digits + punctuation:
            for l in ascii_letters + digits + punctuation:
                # Imprime cada combinación de 4 caracteres separados por espacios
                print(i, j, k, l)

## Enumerar contraseñas de 1 a 4 dígitos (números)
## itertools.product(...) genera el producto cartesiano de iterables.
from itertools import product
from string import digits

## CONTRASEÑA OBJETIVO
target_password = "1234"

#Generador de combinaciones
def crack_numeric(length):
    # Recorre todas las combinaciones posibles de 'length' dígitos
    for combo in product(digits, repeat=length):
        # Une los caracteres del tuple 'combo' en una cadena (por ejemplo: ('1','2','3') → "123")
        guess = ''.join(combo)

        # Compara la combinación generada con la contraseña objetivo
        if guess == target_password:
            # Si coincide, imprime mensaje y termina la función
            print("Contraseña encontrada :D =>", guess)
            return

    # Si el bucle termina sin encontrarla, muestra este mensaje (¡pero ojo, está mal indentado!)
    print("Contraseña no encontrada :(")

#Ejecutamos el algoritmo
crack_numeric(4)


## def crack_numeric(length):      ## recibe un entero
##     for combo in product(digits, repeat=length): ## genera todas las combinaciones posibles con logitud length
##         yield ''.join(combo)    ## devuelve un generador que produce todas las combinaciones de length
## El uso de yield convierte la función en un generador,
##que va devolviendo resultados uno a uno en vez de construir toda la lista en memoria

## for pwd in crack_numeric(4): ## recorre todas las contraseñas posibles de x digitos este ejemplo 4
##     pass # simula comparación segura
## En este ejemplo, no se hace nada (pass),
## pero se podría comparar con una contraseña objetivo.
## print("Listas generadas:", 10**4)